# Generated by Django 3.2.16 on 2022-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='short_effect',
            field=models.TextField(null=True),
        ),
    ]
