# Generated by Django 3.2.16 on 2022-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20221126_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='order',
            field=models.IntegerField(),
        ),
    ]
